

http://localhost:300/location/Cat4/Name4



###

POST http://localhost:300/location HTTP/1.1
content-type: application/json

 {
    "name": "Name4",
    "category": "Cat4",
    "location":[-56.041394,-15.614426]
  }

  
